### ISSUE TITLE
Resource injection into TracerProvider

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#105]
I'm trying to build out some Resources for iOS devices, and I'm having difficulty finding a way to pass a resource into a TracerProvider per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md). Is a parameter for adding a Resource via the TracerProvider constructor something that needs to be added or am I missing something?

It actually seems the static-global structure of this framework creates a difficulty in adding a Resource to the TracerProvider on construction. Or, would it be better to construct a new TracerProvider and update the global variable with the new provider? This doesn't seem like a great solution because it could overwrite a TracerProvider supplied by some other framework. Thoughts?

**Comment by nachoBonafonte** [comment]
The default tracerProvider is constructed using the resources form EnvVarResource, so you can change the Resources by using a environment variable without modifying any code, which is probably not the best option for iOS.

For this case I think currently the best option is constructing a new TracerSdkProvider which uses a Resource attribute, but you don't need to update the global variable if you dont want.

**Comment by nachoBonafonte** [comment]
I have just noticed that the TracerSdkProvider initializer with parameters is not public, will prepare a PR with the fix.

**Comment by nachoBonafonte** [comment]
@bryce-b Let me know if it would work for you with this change or if you have any other proposal

**Comment by bryce-b** [comment]
@nachoBonafonte I didn't have any intended solution for this. This looks like it will work for my use case. 👍 
Thanks for the quick response!

**Comment by nachoBonafonte** [comment]
Solved with #106
