### ISSUE TITLE
Add Otel-protocol metric exporter 

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#107]
I'm going to start working on a metric exporter for the open-telemetry protocol. If there is any existing work or caveats I need to be aware of, please let me know.

**Comment by nachoBonafonte** [comment]
That's really great news!!!
Main caveat is that the opentelemetry-swift metrics API is a bit outdated compared to the open-telemetry protocol, but you can update whatever you think makes sense.

**Comment by bryce-b** [comment]
👍

**Comment by bryce-b** [comment]
@nachoBonafonte I see that your original metric implementation is based off the .net solution, but they've backed away from metrics for the time being, it seems. I'm going to be referencing the java implementation going forward, and try to minimize the amount of changes overall. Right now, I'm looking at adding a Resource reference & InstrumentationLibrary reference to the MetricData object to allow for the generation of [ResourceMetrics](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L28)
Let me know if there are any concerns. If I run into trouble, I'll post in here for help. 
Thanks!

**Comment by nachoBonafonte** [comment]
Yes, it is based off .net implementation, java implementation looked a bit too convoluted for me. But I am not very happy in how it ended up, so feel free to change all that makes sense for you, probably metrics is the area where I have less experience.

**Comment by bryce-b** [comment]
linking #108

**Comment by bryce-b** [comment]
@nachoBonafonte @SergeyKanzhelev This is off-topic for this thread, but I was intending on going to the "Governance Office Hours" on Monday and ask about starting a SIG for this agent. Is that something you guys would be interested in?

**Comment by nachoBonafonte** [comment]
Yes, I think it can be useful for doing some planning and synchronization. Until now I was the only one doing regular work on the project so planning and organization has not been my highest priority.

**Comment by nachoBonafonte** [comment]
Done in #108
