### ISSUE TITLE
Improve Stdout exporter

### ISSUE THREAD

**Issue by nacho-undefinedlabs** [open-telemetry/opentelemetry-swift#11]
Change stdout exporter in line with:

> Generally though we are trying to output to stdout in a form of JSON in a single line. It is more applicable for server side probably where stdout can be consumed programmatically by fluentBit or something like this

Now is only useful for debugging during development

**Comment by RayZhao1998** [comment]
Does it means we need a better output such as JSON?

**Comment by nacho-undefinedlabs** [comment]
Yes, as mentioned, default output should be a one line JSON to stdout (probably checking what other languages implementations are printing), but it should be possible also to configure it to use a format usable for debugging.

**Comment by RayZhao1998** [comment]
Ok, I'll improve it.
