### ISSUE TITLE
Add JSON CollectorExporter in OpenTelemetryProtocol

### ISSUE THREAD

**Issue by vj4iosdev** [open-telemetry/opentelemetry-swift#110]
Trying to export span data in JSON format. Any ideas or suggestions on this?
Quick addition of JSON CollectorExporter will be really appreciable.
Thanks in advance.

**Comment by bryce-b** [comment]
take a look at https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/Stdout/StdoutExporter.swift 
this could be used as a basis for adding a new json specific exporter

**Comment by vj4iosdev** [comment]
Added OtlpTraceJsonExporter. Take a look at [](https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/OpenTelemetryProtocol/trace/OtlpTraceJsonExporter.swift)
