### ISSUE TITLE
add recordException() to span

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#117]
should capture Error, NSError, and NSException

**Comment by bryce-b** [comment]
review https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md

**Comment by bryce-b** [comment]
absolutely! This issue is describing a simple helper method to save users the time of manually adding errors per the exception spec : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/exceptions.md

**Comment by jarrodrobins** [comment]
A 👍 for this issue - this feature would be very useful.
