### ISSUE TITLE
Consider hiding `DefaultSpan`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-swift#121]
As per the Spec, it is desirable hiding the actual type/class, and simply expose it through a factory/static method. In Java, for example, it is created as:

```java
// No DefaultSpan is exposed.
Span span = Span.wrap(spanContext);
```

(btw, this type is now called `PropagatedSpan`, so if you really need to keep it, it makes sense to rename it)

**Comment by nachoBonafonte** [comment]
Wow, thanks a lot for your expedited review, I will review all the issues and will act on them
