### ISSUE TITLE
Consider exposing an empty `Resource`

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-swift#124]
As per the [Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#the-empty-resource), it is recommended to provide a way to quickly create an empty resource, e.g. `Resource.getEmpty()`

**Comment by nachoBonafonte** [comment]
Default constructor already creates an empty resource, is it needed to expose a method just for it? Container classes in Swift usually have their default constructors returning an empty entity
