### ISSUE TITLE
`RecordEventsReadableSpan` needs to initialize member `totalAttributeCount` 

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#136]
If `RecordEventsReadableSpan` is passed a non-empty attribute dictionary `toProtoSpan()` will crash when calculating the number of dropped attributes.
https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/OpenTelemetryProtocol/trace/SpanAdapter.swift#L66

- constructing a `RecordEventReadableSpan` with an attribute dictionary with more than zero attributes (.e.g. 4 attributes)
- New span's `totalAttributeCount` will equal 0, but `span.attributes.count` will be 4
- `protoSpan.droppedAttributesCount = UInt32(spanData.totalAttributeCount - spanData.attributes.count)` will produce a negative number.

**Comment by nachoBonafonte** [comment]
Fixed in #142
