### ISSUE TITLE
Consider splitting out experimental packages

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-swift#138]
A few areas (metrics, semantic conventions, opentracing shim) are still experimental and should be offered as separate packages (with either a `0.x` version or a `-experimental`/`-alpha` suffix).

Related: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#signal-lifecycle

**Comment by nachoBonafonte** [comment]
I will bring this issue to the SIG meeting to choose the preferred solution

**Comment by nachoBonafonte** [comment]
We will change name to include suffixes
