### ISSUE TITLE
Consider simplifying `Baggage` section

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-swift#141]
For a little while we had the same discussion in Java, and we ended up removing `BaggageManager`, offering all functionality through `Baggage.builder()` and module/static functions for `Context` handling (similar to moving them out of `Tracer`).

We also happened to hide other members as `EmptyBaggage`, by providing the same through static methods (i.e. `Baggage.empty()`).

Finally - we removed `DefaultBaggage` and made this the **official** de facto class used underneath.

(Overall I _think_ with all these changes, we made the API surface smaller/simpler).

**Comment by alolita** [comment]
Fixed. Closing issue.
