### ISSUE TITLE
Fix Jaeger exporter is not compiling with Xcode 11.4

### ISSUE THREAD

**Issue by nacho-undefinedlabs** [open-telemetry/opentelemetry-swift#15]
Thrift library is a bit obsolete and dens compile with Swift 5.2, we are using a fork located in [https://github.com/undefinedlabs/Thrift-Swift](https://github.com/undefinedlabs/Thrift-Swift). Update this fork (I have control of that repo) or use another fork with the changes needed to compile. The original library has many forks, changes can be brought from any of those.

**Comment by RayZhao1998** [comment]
I'm working on this.

**Comment by RayZhao1998** [comment]
Just add implementation of makeIterator to solve the compile error. 

A PR has been made to [https://github.com/undefinedlabs/Thrift-Swift](https://github.com/undefinedlabs/Thrift-Swift), please review [it](https://github.com/undefinedlabs/Thrift-Swift/pull/1).

**Comment by nacho-undefinedlabs** [comment]
Merged the PR to Thrift-Swift and released version 1.1.2 that fixes compiling with Swift 5.2.
With this change now Jaeger exporter compiles and passes tests.
Thanks a lot for your contribution.
