### ISSUE TITLE
Consider removing TraceId/SpanId classes

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-swift#152]
This is more of a potential optimization, rather than correctness: in other languages trace and span id exist as primitive types, with utility methods to create/parse them. In Java they are exposed as strings, whereas in Python the exist as integers.

For your consideration ;)

**Comment by nachoBonafonte** [comment]
Being structs themselves I dont think it would perform better using other types, but I will bring it to the SIG meeting to think about it

**Comment by nachoBonafonte** [comment]
Considered but decided to not change it
