### ISSUE TITLE
Add a GitHub action to monitor tests

### ISSUE THREAD

**Issue by nacho-undefinedlabs** [open-telemetry/opentelemetry-swift#16]
Use Scope for swift for  monitoring tests [https://github.com/marketplace/actions/scope-for-swift](https://github.com/marketplace/actions/scope-for-swift)

**Comment by SergeyKanzhelev** [comment]
I can help enabling it for the org. Is it kind of a CI tool?

**Comment by nacho-undefinedlabs** [comment]
Yes, is a tool from my company, free for OpenSource projects, and very useful for tracking test during time.
