### ISSUE TITLE
Add `addMetricProcessor` function to MetricProvider

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#167]
https://cloud-native.slack.com/archives/C01NCHR19SB/p1618582139006900?thread_ts=1618580592.006800&cid=C01NCHR19SB

We need to add consistency between the span provider and metric provider. Currently for metrics you have to initialise your own `MeterProviderSdk` which is not necessary for spans.

Desired syntax:
> OpenTelemetrySDK.instance.meterProvider.addMetricProcessor(metricProcessor)

**Comment by nachoBonafonte** [comment]
Hi @Sherlouk, I created a PR to solve this issue. Let me know what you think.
It allows to customise the configuration of the provider and also added the possibility to add several metric exporters.
