### ISSUE TITLE
 Implementation of the B3 propagation protocol.

### ISSUE THREAD

**Issue by nacho-undefinedlabs** [open-telemetry/opentelemetry-swift#19]
It should be located in /OpenTelemetryApi/Trace/Propagation. 
See [https://github.com/openzipkin/b3-propagation](https://github.com/openzipkin/b3-propagation). 
Java opentelemetry client can be a good reference  for implementation details: [https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/propagation/B3Propagator.java](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/propagation/B3Propagator.java)

**Comment by RayZhao1998** [comment]
I'm working on this now.

**Comment by nacho-undefinedlabs** [comment]
Closed with #26
