### ISSUE TITLE
Update Semantic Conventions to v1.3.0

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#196]
https://github.com/open-telemetry/opentelemetry-swift/blob/main/Scripts/semantic-convention/generate.sh#L7

https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.3.0

We may want to wait for 1.4.0 before picking this up, as it includes mobile-specific conventions which is appropriate to this SIG package.

**Comment by nachoBonafonte** [comment]
I will take a look if it is possible to update to something more up to date
