### ISSUE TITLE
Expose `CallOptions` in OTLP exporters

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#204]
The `TraceServiceClient` & `MetricServiceClient` (full class name like : `Opentelemetry_Proto_Collector_Trace_V1_TraceServiceClient`) are used to export service requests using GRPC via an `export` method ( [example 1](https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/OpenTelemetryProtocol/trace/OtlpTraceExporter.swift#L32))
This `export` method as an optional second parameter, `CallOptions` : https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/OpenTelemetryProtocol/proto/trace_service.grpc.swift#L57

This `CallOptions` provides access to setting [GPRC metadata](https://github.com/grpc/grpc-swift/blob/main/Sources/GRPC/CallOptions.swift) which can be useful for use in setting things like AUTH headers.

I'd like to propose exposing an optional configuration to these exporters to allow passing of a `CallOptions` to the constructor. Maybe something like : 

```
public class OtlpTraceExporter: SpanExporter {
    let channel: GRPCChannel   
    let traceClient: Opentelemetry_Proto_Collector_Trace_V1_TraceServiceClient    
    let timeoutNanos: Int64
    let options: CallOptions?

    public init(channel: GRPCChannel, timeoutNanos: Int64 = 0, options: CallOptions? = nil) {
       ...
   }

    public func export(spans: [SpanData]) -> SpanExporterResultCode {
        ...
        let export = traceClient.export(exportRequest, options)
```

**Comment by nachoBonafonte** [comment]
Totally agree, in fact it looks like a really needed feature

**Comment by bryce-b** [comment]
This actually may be solved by implemented https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md

specifically the OTEL_EXPORTER_OTLP_HEADERS field.
