### ISSUE TITLE
OTel proto's as models?

### ISSUE THREAD

**Issue by heckj** [open-telemetry/opentelemetry-swift#22]
👋 I was just stumbling onto this repo, and noticed that it didn't reflect any of the datamodels from the protobuf IDLs in https://github.com/open-telemetry/opentelemetry-proto

I didn't want to disrupt this, but let you know that I grabbed those core protos and created a swift package to expose them. Wanted to share in case it would be useful to you:

https://github.com/heckj/OpenTelemetryModels

It's just the proto files generated into models, nothing more - but may still be useful to you.

**Comment by nacho-undefinedlabs** [comment]
Thanks, they will surely be useful when targeting the OpenTelemetry Collector, it can be also useful now to compare with our current data model for changes or improvements

**Comment by heckj** [comment]
Now that I've wallowed around in some of the basics, read through this code and some of the other clients, and the specs - are you aiming at adding anything to this codebase that serializes to the protobuf spec'd objects, or are you anticipating that's all something that should reside entirely in an exporter?

**Comment by nacho-undefinedlabs** [comment]
Yes, we need to add a exporter to this codebase to send span data to the OpenTelemetry collector, and there is where I think that this protobuf code should go. What other uses were you thinking for it?

**Comment by heckj** [comment]
My personal project goal is tracing over a peer to peer connection, which if it used this setup would be a fairly "non-standard" tracing thing - but could possibly be an external "exporter". I was hoping that I could use the protobuf serialization to store spans relatively compactly for later transmission (as opposed to the constant "flow of spans" that most clients utilize) - and then inspect things when I've collected the data together.

In OpenTelemetryModels I generated the swift code from the protobufs and start fiddling with it, and then circled back after I had some experience with it to see what was developing here. When I noticed that the protobuf pieces didn't yet seem to be included, I wasn't sure how this might evolve forward and how I might leverage/extend or fork and use it for my crazy purposes.

**Comment by nacho-undefinedlabs** [comment]
I can imagine the exporter for the Opentemetry collector having a setting so it allows to output the protobuf serialization before sending to the collector. What do you think about it? It would allow the code to be in the official repo and to be mantained if the API changes during development.
