### ISSUE TITLE
We should split out features with external dependencies that also support CocoaPods into separate repositories (e.g., Reachability)

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/opentelemetry-swift#225]
Hi - 

First, apologies for the wall of text.

We (Splunk) are working on an Otel-based mobile RUM solution ([https://github.com/signalfx/splunk-otel-ios](https://github.com/signalfx/splunk-otel-ios)).  For iOS this is based on otel-swift, and we have been very happy with it.  One difficulty we've encountered in early trials is with customers using CocoaPods, and having difficulties with duplicate libraries being imported (symbol defined twice / linking errors).  It seems that CocoaPods and Swift Package Manager (SPM from here on out), not knowing anything about each other, don't really agree on which version to install, not installing two copies, etc.  For libraries which are only exposed through SPM, this is not an issue, since our mobile agent, the otel api and sdk, most of its dependencies, etc. are all only offered as swift packages and not through any other package manager.

We have a crash reporting feature based on the popular [PLCrashReporter](https://github.com/microsoft/plcrashreporter) library, which is exposed through **both** SPM and CocoaPods, and this led to issues.  Our solution was to package this functionality as a separate Swift package, in a separate repo, and allow CocoaPods users to opt into using it only if they weren't already using PLCrashReporter (directly or indirectly through another library) or were otherwise able to resolve the linking conflict.  In particular, we found that having **separate Swift targets was an insufficient solution**, because it appears that in SPM dependencies are scoped and resolved at the full package level (if a package contains targets A and B, which depend on external libraries A1 and B1 respectively, and you only use A in your app, SPM will still try to resolve B1).

While I like the idea of having instrumentation to report network status, I'm concerned that adding Reachability as a dependency is problematic for CocoaPods users, as Reachability is a fairly popular library, and offers CocoaPods support.  By carefully limiting and scoping our use of third-party libraries, we can more easily accommodate users of other package managers.

Thoughts on this?

**Comment by nachoBonafonte** [comment]
This is an interesting problem, and a problem not easily solved. SPM and Swift have some limitations when using the same dependencies from different sources that make it difficult to handle as you said, but also makes it very difficult to add new features to Opentelemetry without risking the linking side. 

I have been lately using in other projects `@_implementationOnly import` instead of simply using `import` for the third party modules that you simply use and don't export any of their symbols. It solves the linking errors although can report warnings of repeated libraries. We could try with a similar approach for this problem and see how it work out. 

This is an important topic that will probably need more ideas and approaches, how about talking about it in the Swift SIG meeting?

**Comment by johnbley** [comment]
Two particular pain points I've identified with some toy projects:
- A) A project that uses CocoaPods, uses Reachability as a pod, and then imports otel-swift *and* chooses to use the NetworkStatus target.  This will compile fine, but at runtime produces the error message `Class _TtC12Reachability12Reachability is implemented in both <blah> and <blah2>.  One of the two will be used. Which one is undefined.` (if the developer actually notices it).  Further, if the app uses Reachability 4 (and otel-swift uses Reachability 5), the app will randomly (50%) crash due to breaking API changes.
- B) A project using only Swift Package Manager, that uses Reachability 4 (through SPM).  Attempting to add the otel-swift package results in the following error *without* even getting to the screen to specify that the project does not want to use the NetworkStatus target therein:

<img width="715" alt="AddPackage" src="https://user-images.githubusercontent.com/5139839/131382330-48f2ff2e-321f-4ea2-bb59-52c000a021d3.png">

**Comment by nachoBonafonte** [comment]
> A) A project that uses CocoaPods, uses Reachability as a pod, and then imports otel-swift and chooses to use the NetworkStatus target. This will compile fine, but at runtime produces the error message Class _TtC12Reachability12Reachability is implemented in both <blah> and <blah2>. One of the two will be used. Which one is undefined. (if the developer actually notices it). Further, if the app uses Reachability 4 (and otel-swift uses Reachability 5), the app will randomly (50%) crash due to breaking API changes.

This one is expected, if you are using two dependences that have incompatible versions of the same third dependence, then you have a real problem, and a problem that is not solvable in any way: e.g. if using Cocoapods it would not even resolve the dependencies. I don't see how we could improve it except:
 * Avoid using any third party dependence, which would limit the scope of functionality we can provide for free
 * Using the broader versioning for our third party dependencies, so we reduce the possibilities for the issue
 * Any other option?

> B) A project using only Swift Package Manager, that uses Reachability 4 (through SPM). Attempting to add the otel-swift package results in the following error without even getting to the screen to specify that the project does not want to use the NetworkStatus target therein

This one is weird. I would say that it is a bug or limitation in SPM. Just by referencing a package it doesn't mean that you are going to use the target that references the third party dependence so it should not be resolved. But said that, I only see these options to minimize the damage: 
* as in A: remove all third party dependencies or try to use the lowest version possible of the third party dependency and support up to the newest version so we reduce the damage as much as possible
* move intrumentations to a different repository, which would only solve the issue if you are not going to use any instrumentation at all or you would face the same problem
* move each instrumentation to its own repository, which would mean having 10 different repositories the user would have to know and configure for their projects
* Any other solution?

None of these solutions is perfect, and all have lots of pros and cons, but in my opinion the best solution for both issues is allowing third party dependencies but adding support for the lowest version possible.

**Comment by johnbley** [comment]
Awesome, thanks!
