### ISSUE TITLE
Fail in send by ZipkinTraceExporter  

### ISSUE THREAD

**Issue by lzctxwd** [open-telemetry/opentelemetry-swift#257]
An exception occurs when I use ZipkinTraceExporter to report the HTTP request sent by alamofire

Dependent address of alamofire is

    .package(name: "Alamofire", url: "https://github.com/Alamofire/Alamofire.git", from: "4.9.1"),

A simplified example would look like this:

    func alamofireRequest() {
        Alamofire.request("http://100.83.82.9:8083/pay/payOrder", method: .get, parameters: nil, encoding: URLEncoding.default, headers: nil)
    }
    let spanProcessor = SimpleSpanProcessor(spanExporter: ZipkinTraceExporter.init(options:ZipkinTraceExporterOptions(endpoint: "http://xx.xx.xx.xx:9411/api/v2/spans")))
    OpenTelemetrySDK.instance.tracerProvider.addSpanProcessor(spanProcessor)

    let networkInstrumentation = URLSessionInstrumentation(configuration: URLSessionInstrumentationConfiguration())

    alamofireRequest()

Error occurred at URLSessionInstrumentation.urlSessionTaskWillResume, I find the status of queue is draining

Printing description of queue:

    OS_dispatch_queue_serial: io.opentelemetry.ddnetworkinstrumentation[0x100b979f0] = { xref = 10, ref = 1, sref = 1, target = com.apple.root.default-qos.overcommit[0x100941100], width = 0x1, state = 0x0060002800002202, draining on 0x2203, in-barrier}

**Comment by nachoBonafonte** [comment]
Looking into this issue now, I can confirm the problems

**Comment by nachoBonafonte** [comment]
I have created a PR that solves the problem: #270 
With previous code concurrent network requests would only report the first request, failing to report the rest.

**Comment by lzctxwd** [comment]
@nachoBonafonte I have verified that the link information of multiple requests is also normal. Thank you very much for your help
