### ISSUE TITLE
OC project references this project

### ISSUE THREAD

**Issue by lzctxwd** [open-telemetry/opentelemetry-swift#267]
Whether this project supports the use of the OC project. I tried to introduce this project into the OC project, which can be initialized, but it did not take effect when I used the HTTP request to intercept it

**Comment by lzctxwd** [comment]
@nachoBonafonte Yes, I use NSURLsession, and initialized in swift like it:

    class Test: NSObject {
        @objc func initInstrumentation() {
            let spanProcessor = BatchSpanProcessor(spanExporter:     ZipkinTraceExporter.init(options:ZipkinTraceExporterOptions(endpoint: "http://100.83.82.43:9411/api/v2/spans")))
            OpenTelemetrySDK.instance.tracerProvider.addSpanProcessor(spanProcessor)
            let networkInstrumentation = URLSessionInstrumentation(configuration: URLSessionInstrumentationConfiguration(shouldInstrument: {
                if $0.url?.absoluteString == "http://xx.xx.xx.xx:9411/api/v2/spans" {
                   return false
                }
                return true}))
        }
    }

Then it is called in the Objective-C project project like it:

    Test *test = [[Test alloc] init];
    [test initInstrumentation];

**Comment by nachoBonafonte** [comment]
I have recreated a Obj-C small project, and have started simple,  just using StdoutExporter like this:

> class Test: NSObject {
>     @objc func initInstrumentation() {
>         let spanProcessor = BatchSpanProcessor(spanExporter: StdoutExporter(isDebug: true))
>         OpenTelemetrySDK.instance.tracerProvider.addSpanProcessor(spanProcessor)
>         _ = URLSessionInstrumentation(configuration: URLSessionInstrumentationConfiguration())
>     }
> }
And it works as expected for me, can you confirm if if it also works for you?

I am attaching the sample project here
[OTTEST.zip](https://github.com/open-telemetry/opentelemetry-swift/files/7461668/OTTEST.zip)

**Comment by lzctxwd** [comment]
@nachoBonafonte Thank you very much. Through your example, I found some problems I cited. Now the problems have been solved
