### ISSUE TITLE
Elastic Language Display

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#275]
Elastic shows a language icon next to each project based on the metadata. As you can see, it doesn't work for this project currently 😭  I wonder if there's anything we can do to improve the support here? Or whether we can reach out to somebody with Elastic connections etc?

<img width="302" alt="Screenshot 2021-11-09 at 4 10 30 pm" src="https://user-images.githubusercontent.com/15193942/140961241-585a52ab-d530-49f2-858b-33fd6db3b462.png">

Worth noting the middle one here uses `agent.name | otlp` and nothing else in there. Might be an interesting option?

**Comment by nachoBonafonte** [comment]
Probably @bryce-b can be helpful here

**Comment by bryce-b** [comment]
🤔 which version are you using? I'll see what I can do.

**Comment by Sherlouk** [comment]
Just checked, we're on v7.10.2.

**Comment by bryce-b** [comment]
Ah yeah, I think otel/ios support was added in 7.14

**Comment by Sherlouk** [comment]
I'll speak to the team and ask if/when they're planning on updating.

Will close this ticket off on the proviso that it's working if we update.
