### ISSUE TITLE
thread-safety within the traceprovider context?

### ISSUE THREAD

**Issue by heckj** [open-telemetry/opentelemetry-swift#28]
didn't know how to ask otherwise, so I'm opening an issue with the question - 

The overall OpenTelemetry spec makes some specific recommendations related to thread safety, in particular that [Tracer, Span and Link should be able to be called concurrently](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/concurrency.md). I'm not seeing anything in this current codebase that covers that sort of protection, so I wanted to ask how you were planning on tackling some of that - and where you expected the implementation to need some adjustment based on that.

**Comment by heckj** [comment]
To provide a little more context, I was looking at how this might be done and how others have done it - and there appears to be two mechanisms that people choose between: using the [low-level Lock mechanisms that swift-nio](https://forums.swift.org/t/swift-nio-thread-safety-between-channel-handlers/29529) has in place, or leveraging [Dispatch](https://developer.apple.com/documentation/DISPATCH) from within Foundation and wrapping updates in serial contexts or such. 

I saw in the linked forum post that Dispatch isn't as performant, but I've not measured or done any analysis myself and can't really back that up - or have any way of quantifying what "not performant" means and how much it might impact things.

**Comment by nacho-undefinedlabs** [comment]
Thread safety and synchronisation is an area that is currently under heavy development in Swift, so we can expect big changes in this area for Swift in the near future. There is a proposal in review about [Low-Level Atomic Operations](https://forums.swift.org/t/se-0282-low-level-atomic-operations/35382). So in the meantime I think that going with  [Dispatch](https://developer.apple.com/documentation/DISPATCH) (much more documented and with more development experience from almost anyone) is a more productive way than the low-level Lock mechanism of swift-nio.
