### ISSUE TITLE
No such module 'Atomics'

### ISSUE THREAD

**Issue by schultyy** [open-telemetry/opentelemetry-swift#299]
When I add these OpenTelemetry libraries to a Swift iOS application:

- OTLP Exporter
- OpenTelemetrySdk
- OpenTelemetryApi
- OpenTelemetryProtocolExporter

I'd expect the project to build without errors. Instead, I receive this error:

```
/Users/<USER>/Library/Developer/Xcode/DerivedData/testing-dfttyvqmqotigccnmfwvzmrlmfcp/SourcePackages/checkouts/opentelemetry-swift/Sources/OpenTelemetrySdk/Trace/RecordEventsReadableSpan.swift:6:8: No such module 'Atomics'
```

Adding `swift-atomics` as a dependency to my project does not help. Am I missing another dependency or setting here?

Reproducible with:
- XCode 13.3.1
- macOS 12.3.1
- iOS 15.4

**Comment by nachoBonafonte** [comment]
`OTLP exporter` is not a library but an executable, in fact is an example application of the API usage.  But is true that Xcode 13.3.1 shows it as a library when importing the opentelemetry project and allows you to link it. 

Just remove `OTLP exporter`  from the link step and everything should work as expected ( the swift-atomics dependency should be transparently handled by Xcode, so you don't need to manually link it)

Hope it helps

**Comment by schultyy** [comment]
@nachoBonafonte Thanks so much! That helped me to get unstuck! Closing this.
