### ISSUE TITLE
Crash in Metrics MeterSdk.collect

### ISSUE THREAD

**Issue by iyxcCode** [open-telemetry/opentelemetry-swift#302]
When we use the Metrics module, we found that there are multiple crash situations, which appear in the `collect` of `MeterSdk`. Similar crash scenarios seem to occur in `UIApplication WillEnterForeground`. Check the Crash information, APP enters the foreground from the background, Metrics may have memory issues. Please help to look at the problem. 

<img width="1554" alt="22" src="https://user-images.githubusercontent.com/10302223/170034517-81d019a4-e7c5-4639-baa5-e11fb678d78b.png">
<img width="1722" alt="23" src="https://user-images.githubusercontent.com/10302223/170034551-05cc7fa7-b1d0-4312-b56d-3115d1d71b08.png">
<img width="1540" alt="24" src="https://user-images.githubusercontent.com/10302223/170034558-01ff5fca-4ff7-435a-9ec3-b641eb164226.png">

**Comment by nachoBonafonte** [comment]
Hi iyxcCode, 
Its not easy with that information to know what is really happening and why it is crashing, could you provide some more information. I am seeing some Objective C related code and some bridging code in the callstack: NSInvalidArgimentException, NSCFNumber obj_exception_throw. Opentelemetry-swift includes no Objective-C code. I am afraid I cannot help you without more information:
 * Are you implementing your own Metrics?, are you calling ObjC code from there?
 * Have you been able to reproduce it with debug code, so we can get proper method and line information?. If only crashes in release, could you symbolicate the output?
 * Do you have a simple project that I could use to reproduce it?
