### ISSUE TITLE
Cannot allocate memory error

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#310]
When using `DefaultResources().get()` in my application, I get the error below printed to debug console.

```
error #12: Optional("Cannot allocate memory")
```

I have mapped this to this line of code: https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Instrumentation/SDKResourceExtension/DataSource/DeviceDataSource.swift#L33

This is running on Xcode 14 beta 2 against an iOS 16 simulator.

**Comment by nachoBonafonte** [comment]
Yes, it looks so, I will take a look
