### ISSUE TITLE
OTLP exporter doesn't work with v0.54.0 collector

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#311]
Downgraded to v0.50.0 as per sample project and it works as expected. Perhaps some breaking change in between?

No errors in iOS app or in collector logs. Just seems to get lost in the ether.

**Comment by nachoBonafonte** [comment]
It should be working with latest versions  (0.55 and up), could you please check

**Comment by nachoBonafonte** [comment]
@Sherlouk ?

**Comment by Sherlouk** [comment]
Apologies Nacho, it's on my TODO but I've not had a chance to get to it just yet.

**Comment by nachoBonafonte** [comment]
No worries, just mentioned to confirm you were receiving the update. We think that it was broken on the collector side for some version/versions and that they fixed it after that, Bryce said it was working for him with the latest.

**Comment by Sherlouk** [comment]
Quick check is looking positive ☺️ will re open if I start to see issues again
