### ISSUE TITLE
B3 Propagator should left-pad 64-bit trace IDs with zeros

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-swift#32]
As noted in https://github.com/open-telemetry/opentelemetry-go/issues/686 and discussed at the SIG Spec meeting today, we should left-pad 64-bit trace ID values in B3 propagators to allow for interoperability with systems that produce 64-bit trace IDs.  It appears that the [traceID initializer](https://github.com/open-telemetry/opentelemetry-swift/blob/master/Sources/OpenTelemetryApi/Trace/TraceId.swift#L129) does not allow for trace IDs that are less than 32 hex digits.

**Comment by nacho-undefinedlabs** [comment]
There are several TraceId initializers( all the methods with name `init` are initialisers), some of them can be used for initialising with part of the bytes set to 0 like [this](https://github.com/open-telemetry/opentelemetry-swift/blob/master/Sources/OpenTelemetryApi/Trace/TraceId.swift#L39), or [this](https://github.com/open-telemetry/opentelemetry-swift/blob/master/Sources/OpenTelemetryApi/Trace/TraceId.swift#L73)
