### ISSUE TITLE
Update proto defs for compatibility with OTEL collector 0.58.0+

### ISSUE THREAD

**Issue by laban-eilers-simplisafe** [open-telemetry/opentelemetry-swift#333]
When attempting to export spans via the OTLPTraceExporter to an OTEL collector at version 0.58.0+, the Swift SDK currently fails silently. It makes successful GRPC calls to the collector, but the collector doesn't log any received spans.

I've been told by @vvydier that this is because of some backwards incompatible protobuf definition changes in the OTEL collector. He says the fix is to pull the latest protobuf definitions and recompile the swift SDK.

**Comment by vvydier** [comment]
OTLPTraceExporter is sending spans. It's the OTEL collector that is not accepting them as the protobuf files have changed in a newer version. Its will be easier to debug if OTEL collector (with the debug option turned on) reports that is receiving incompatible spans.

**Comment by vvydier** [comment]
@nachoBonafonte has been adding the OTEL collector version supported in the release notes, but I agree that it would be easier to debug if the collector reported this incompatibility instead of silently dropping them.

**Comment by vvydier** [comment]
OTEL collector does report if there is mismatch in the telemetry data its receiving. Closing the issue
