### ISSUE TITLE
Missing required module 'CNIOAtomics'

### ISSUE THREAD

**Issue by jvigneshcs** [open-telemetry/opentelemetry-swift#364]
I am working on small Xcode Framework project using opentelemetry-swift.
I will share the **XCFramework** with the client and they will add the opentelemetry-swift dependency using SPM.
I have set **Build Libraries for Distribution** to **YES**,
so I get the following warning in my Framework project,
>Module 'OpenTelemetrySdk' was not compiled with library evolution support; using it means binary compatibility for '***WrapperSDK' can't be guaranteed

while importing the following in my project,
- import OpenTelemetryApi
- import OpenTelemetrySdk
- import OpenTelemetryProtocolExporter
- import NIOHTTP2
- import GRPC

And my **Link Binary With Binaries** under **Build Phases** of my Framework project is as follows,
<img width="786" alt="Screenshot 2023-01-03 at 11 48 12 AM" src="https://user-images.githubusercontent.com/1597360/210308232-82c87404-8166-4197-957c-3de95d214032.png">

When I generate ***.framework** and integrate it in the iOS sample application, the sample app gets build and runs fine.
If I generate ***.xcframework** with all supported platforms and integrate it in the iOS sample application, I got the following error
> error: missing required module 'CNIOAtomics'

Then I tried the solution referred [here](https://github.com/grpc/grpc-swift/issues/683#issuecomment-927008786).
And my **Link Binary With Binaries** under **Build Phases** of my Sample iOS application is as follows,
<img width="781" alt="Screenshot 2023-01-03 at 11 38 51 AM" src="https://user-images.githubusercontent.com/1597360/210307557-cbd3cdde-6636-4483-af16-d839e6906dda.png">
And I get the following errors,
> error: module map file '/MyWorkspaceDirectoryGoesHere/Build/Intermediates.noindex/GeneratedModuleMaps/CNIOAtomics.modulemap' not found
error: failed to build module '***WrapperSDK' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug
error: missing required module 'CNIOAtomics'

How to resolve these errors?

**Comment by nachoBonafonte** [comment]
Have you thought about adding explicit dependency on NIO to your framework or maybe embedding the opentelemetry-swift libraries in your xcframework so the client dont need to include it themselves? For the libraries you are including,  NIO is a transitive dependency on GRPC that is used by OpentelemetryProtocolExporter, so cannot control it from the OPentelemetry project

**Comment by jvigneshcs** [comment]
@nachoBonafonte, I made the following changes to my Framework project and iOS sample application,
<img width="784" alt="Screenshot 2023-01-03 at 7 05 01 PM" src="https://user-images.githubusercontent.com/1597360/210367538-02cff15a-cefa-480e-ab18-31bda8061e3a.png">
<img width="783" alt="Screenshot 2023-01-03 at 7 06 21 PM" src="https://user-images.githubusercontent.com/1597360/210368378-ece0acc9-ed12-4039-9bff-03d9aec85008.png">

Still I get the following errors,
> error: missing required module 'CNIOAtomics'
error: failed to build module '***WrapperSDK' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug

Am I doing anything wrong?

**Comment by nachoBonafonte** [comment]
Another option I can think of is using `@_implementationOnly import` instead of only `import` for the otel-swift libraries inside your code

I am also distributing some otel-swift libraries inside another xcframework, but I am embedding them inside and also don't use OpentelemetryProtocolExporter library, if that can give you some clues for your issue.

**Comment by jvigneshcs** [comment]
> maybe embedding the opentelemetry-swift libraries in your xcframework

Can you share any link or tell me how to do this (Embedding libraries inside xcframework)?

**Comment by nachoBonafonte** [comment]
I mean building a framework or xcframework with them and embedding them later in your own xcframework, there is an option directly in xcode when linking frameworks.

But in the way you are linking the libraries currently, they are already included in your xcframework as they are static libraries, have you tried not linking the client app with opentelemetry and only to your xcframework?

**Comment by jvigneshcs** [comment]
> have you tried not linking the client app with opentelemetry and only to your xcframework?

I just tried your suggestion now, I can able to build and generate xcframework successfully from my Framework project and when I use that xcframework in my client app, I get the following error
> error: no such module 'GRPC'

But in my framework project I have linked GRPC library.
<img width="784" alt="Screenshot 2023-01-03 at 7 05 01 PM" src="https://user-images.githubusercontent.com/1597360/210367538-02cff15a-cefa-480e-ab18-31bda8061e3a.png">

**Comment by nachoBonafonte** [comment]
So you want to use GRPC independently from otel in the client app? Then you probably need to use a full SPM project to handle the dependencies instead of Xcode, which in my experience struggle when trying to use transitory SPM dependences. I am running out of ideas...

**Comment by jvigneshcs** [comment]
> So you want to use GRPC independently from otel in the client app?

**No**, I'm using GRPC in my framework project to configure `ClientConnection` and `OTLPTraceExporter`,

`client = ClientConnection.usingPlatformAppropriateTLS(for: eventLoopGroup).connect(host: host, port: port)`
`let otlpTraceExporter = OtlpTraceExporter(channel: client, config: configuration)`

**Comment by nachoBonafonte** [comment]
If you prepare a sample framework and project that can reproduce your issue I can take a look myself, but I have no more ideas in how to solve it for now, sorry.

**Comment by jvigneshcs** [comment]
Sure I'll do that.

**Comment by jvigneshcs** [comment]
@nachoBonafonte, I have created a simple framework and project to reproduce the error. Kindly have a look at it.
Repository is [here](https://github.com/jvigneshcs/otelwrapper). 
After cloning the repository, execute the following command to generate **`OtelWrapper.xcframework`**

`./generateXCFramework.sh -p 'iOS;iOS Simulator'`

**Comment by nachoBonafonte** [comment]
I have been playing with your test project, and have not had any success so far, what I have seen is that it is not related to opentelemetry-swift project, if you remove all the opentelemetry code and references from the framework code and leave only GRPC and NIO references you end up with the same issue.
[WrapperAPI.swift.zip](https://github.com/open-telemetry/opentelemetry-swift/files/10353300/WrapperAPI.swift.zip)

**Comment by nachoBonafonte** [comment]
We have the opentelemetry-swift SIG meeting later today, I will bring this topic to know how other are handling with this limitations. I will post it here what I can get there.

**Comment by jvigneshcs** [comment]
Currently I'm using your other suggestion of using @_implementationOnly to distribute the framework to the client app.

**Comment by nachoBonafonte** [comment]
Should we close this issue then?
