### ISSUE TITLE
URLSession instrumentation - when to initialize

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-swift#373]
I tried to use the URLSession instrumentation. The README says:
> Initialize the class with URLSessionInstrumentation(configuration: URLSessionInstrumentationConfiguration()) to automatically capture all network calls.

I did that but saw no spans from my calls. After some digging, I moved this line to run after the SDK is initialized which solved the problem.

I guess it makes sense, but it's a very easy mistake to do. I suggest adding this information to the README and to `opentelemetry.io`

**Comment by nachoBonafonte** [comment]
It should be updated now in documentation
