### ISSUE TITLE
No such module 'DequeModule'

### ISSUE THREAD

**Issue by nmilev-scribe** [open-telemetry/opentelemetry-swift#384]
While trying to build the project after adding the `opentelemetry-swift` package, we get the following error:
```
No such module 'DequeModule'
```
in NIOCore -> AsyncSequences -> NIOAsyncSequenceProducer.
We added the package using the menu: File -> Add packages..., then pasting this repo's GitHub url in the Search field and selecting the project to add it to (as opposed to Pods). We also selected the "Up to next major version" dependency rule.
To be frank, we tried a ton of combinations (adding to project instead of to Pods, adding with a fixed 1.4.0 version, etc.). We also tried installing [`swift-nio`](https://github.com/apple/swift-nio) before this package, but the project build fails nonetheless.

Any ideas on how we might resolve this?

**Comment by jaronoff97** [comment]
@nmilev-scribe i'm experiencing the same issue, were you able to figure out a fix?

**Comment by nachoBonafonte** [comment]
I cannot reproduce the issue on my side, can you provide a sample project that reproduces it? Is it a specific import which makes it fail? 

It is for sure a dependence in apple provided frameworks (probably grpc-swift which itself has lots of dependences) that might be clashing with different versions. In my local test it doesnt fail and I can find the DequeModule in a package called swift collections.

**Comment by jaronoff97** [comment]
odd, i literally created a new xcode project, add otel-swift, and the build failed. Yeah I imagine it's upstream as well, just not sure where its supposed to go :(

**Comment by emosiony** [comment]
@nmilev-scribe  i'm experiencing the same issue, were you able to figure out a fix?

**Comment by nachoBonafonte** [comment]
Have you tried with HTTP/OTLP exporter? What is your deployment target?
