### ISSUE TITLE
Separate OTLP Exporter HTTP from gRPC

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/opentelemetry-swift#389]
Currently the gRPC and HTTP exporters (using the OpenTelemetry Collector Protocol) are both in the same package. 

However, the gRPC exporter has heavy dependencies on GRPC and NIO - something which isn't true for the HTTP exporter.
In my testing, this change alone increases the compile time by many minutes in my project.

It appears we would still need the SwiftProtobuf dependency, but overall the separation here would provide an OpenTelemetry solution with very few dependencies (just Protobuf) and a much lower compile time.

![Image](https://user-images.githubusercontent.com/15193942/224482402-d5be63aa-18cf-444f-bfe6-47764cf77e76.png)

Zoomed out far because of just how many modules this project adds, but you can see just how many slow/red dependencies could be removed by performing this change (and us moving to HTTP rather than gRPC).

**Comment by nachoBonafonte** [comment]
Yes, this is a topic we talked about when merging this change, GRPC and NIO dependencies are really complex and are already causing issues to other users, I will bring the topic back to the next SIG meeting so we can take decisions here. Main concern was duplicity of code, but could be worked out.

**Comment by nachoBonafonte** [comment]
We are going to work in this direction, @kevinearls will start working on separating it
