### ISSUE TITLE
NIOHTTP1.HTTPPArserError error 22

### ISSUE THREAD

**Issue by chorgo** [open-telemetry/opentelemetry-swift#392]
Hi,

I'm using a pretty default implementation of the sdk:

`
 public init(hostAndPort: ClientConnection.HostAndPort, serviceName: String, instanceId: String) {
        let otlpConfiguration = OtlpConfiguration(timeout: OtlpConfiguration.DefaultTimeoutInterval)
        let grpcChannel = ClientConnection.connect(hostAndPort)
        let traceExporter = OtlpTraceExporter(channel: grpcChannel, config: otlpConfiguration)
        tracerProvider = TracerProviderBuilder().add(spanProcessor: BatchSpanProcessor(spanExporter: traceExporter))
            .with(resource: Resource(attributes: [
                ResourceAttributes.serviceName.rawValue: .string(serviceName),
                ResourceAttributes.serviceInstanceId.rawValue: .string(instanceId),
            ]))
            .build()

        OpenTelemetry.registerTracerProvider(tracerProvider: tracerProvider)
        let configuration = URLSessionInstrumentationConfiguration()
        networkInstrumentation = URLSessionInstrumentation(configuration: configuration)
    }
`

The spans are recorded correctly, but never get sent to our backend. Inspecting the local traffic with Proxyman I'm getting the following error:

`The operation couldn’t be completed. (NIOHTTP1.HTTPParserError error 22.) (code=22)`

Does anybody have an idea what's going on?

**Comment by bryce-b** [comment]
I'm going to assume this issue is resolved since there was no response.
