### ISSUE TITLE
Any alignment or reuse possible with jaeger-swift?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-swift#4]
From @lakamsani in https://github.com/open-telemetry/community/issues/261

> @nacho-undefinedlabs I assume you already took a look at https://github.com/wayfair/jaeger-swift . Can we leverage anything from there or do you see that also evolving into another independent Open Telemetry Swift implementation (from the currently Open Tracing/Jaeger focussed implementation).

**Comment by nacho-undefinedlabs** [comment]
As mentioned in original thread, all the specific implementations written for Open Tracing or OpenCensus, should evolve into span exporters/processors in Open Telemetry. That is basically the goal of the project, having a single set of system components and language-specific telemetry libraries where all the solutions can be build on top.

The OpenTelemetry-swift project already includes a somewhat basic Jaeger exporter, we could leverage the project to improve the current exporter.
