### ISSUE TITLE
Sending a Log to an OpenTelemetry Collector

### ISSUE THREAD

**Issue by jamonia** [open-telemetry/opentelemetry-swift#416]
I know that "Logs are considered beta quality," but I would like to test it out anyways! 

I have tried to register the LoggerProviderSdk and get a Logger that can provide a logRecordBuilder and an eventBuilder, both capable of emitting. But no logs reach my OTel Collector. 

Is it possible to do this with the current state of the integration?

If so, could someone give me a mega-barebones example - or point me in the right direction?

Any help would be eternally valued! 🙂

**Comment by bryce-b** [comment]
This could be an issue between the version of the collector you're running and the agent. I'll add a logger example to `Examples/`

**Comment by jamonia** [comment]
Thank you so much, @bryce-b! It works like a charm! You made my day! 😎
