### ISSUE TITLE
Status on Metrics API

### ISSUE THREAD

**Issue by frederikbrinck** [open-telemetry/opentelemetry-swift#417]
Hello! 

I have been using the library as a backend to an instrumented an iOS application. Specifically, my application sends metrics to an otel-collector that re-exports them to prometheus. I have run into some issues using counters and gauges. For instance, 

* the counters are checkpointed but are still sent to the otel collector with the `cumulative` tag and not the `delta` tag.
* counters wraps sums that have their [monotonicity](https://github.com/open-telemetry/opentelemetry-swift/blob/f0bdf8638b661a9e72b9188530b2f5c1bcee8b84/Sources/Exporters/OpenTelemetryProtocolCommon/proto/metrics.pb.swift#L513) set to false per default
* [isShortLived](https://github.com/open-telemetry/opentelemetry-swift/blob/f0bdf8638b661a9e72b9188530b2f5c1bcee8b84/Sources/OpenTelemetrySdk/Metrics/CounterMetricSdk.swift#L15) is set to true by default meaning that counters are reset on every metrics export

I see that these issues are to be expected as the metrics API is not up-to-date. Moreover, there is currently a bigger refactor and feature update taking place in this pull request: https://github.com/open-telemetry/opentelemetry-swift/pull/378. 

I was hoping to get answers to the following:

* What is the state of the current metrics implementation
* What is the roadmap for getting it up to date with the Stable otel spec?

I appreciate all the hard work going into this, it is very valuable!

**Comment by nachoBonafonte** [comment]
I will answer them in reverse order :

>What is the roadmap for getting it up to date with the Stable otel spec?

The latest Stable otel spec metrics landed this week to the main branch, they include `Stable` prefix while transitioning, and the source code is in the `Metrics/Stable` folder for both OpenTelemetryApi and OpenTelemetrySdk. They should be fully functional but are still alpha/beta quality. Everything in the project related to metrics will end up transitioning to use them.

> What is the state of the current metrics implementation

It is in stand-by mode, we are going to keep them for a time while we transition everything, but will be eventually renamed and removed from the project.

**Comment by nachoBonafonte** [comment]
Version 1.5.1 already includes the new metrics
