### ISSUE TITLE
'Meter' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by tumlw** [open-telemetry/opentelemetry-swift#418]
Hi otel-swift team,
Recently Apple just added `Meter` as a new type of metric and metric handler.
ref: https://github.com/apple/swift-metrics/releases

This will affect on latest release of otel-swift 1.5.0 where Meter is same class def.
Please consider resolve this issue asap due to dependencies issue

**Comment by zankyn123** [comment]
me too, pls support @nachoBonafonte

**Comment by nachoBonafonte** [comment]
Do you have an easily reproducible way of making it fail?

**Comment by tumlw** [comment]
@nachoBonafonte 
on Otel-swift dependencies:
- depend on Swift-metrics with latest release

However, on version 2.4.0 Apple just added Meter as a new type of metric and metric handler.
which does not impl on 2.3.4

Therefore when resolve package for otel-swift, newest version of Swift-metrics implemented.
class Meter already taken by Apple and not be able to use by Otel-swift

**Comment by nachoBonafonte** [comment]
Can you check now with the latest changes in the repository?

**Comment by nachoBonafonte** [comment]
@tumlw or @zankyn123, can you confirm it is working on your side with main branch?

**Comment by tumlw** [comment]
@nachoBonafonte  sorry for late reply, i just have some health problem.
Thank you and respect for your work!
It works on master branch but too risk to point to this.
could you make it to release? @nachoBonafonte
