### ISSUE TITLE
Update OTLP to 0.20.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-swift#422]
OTLP 0.20.0 was released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.20.0

It is also the release candidate for upcoming 1.0.0.

Please update the OTLP exporter to use OTLP 0.20.0.

**Comment by tigrannajaryan** [comment]
@open-telemetry/swift-maintainers can you please take a look and tell if v0.20.0 works for you? We are planning to declare OTLP 1.0 next week and any changes after that are going to be much harder (if not impossible).

**Comment by tigrannajaryan** [comment]
@open-telemetry/swift-maintainers have you had a chance to look at this?

**Comment by Sherlouk** [comment]
I'm not sure the above group is working, at least it's not resolving for me.

@nachoBonafonte - are you able to try an upgrade using the script we have?

**Comment by tigrannajaryan** [comment]
The TC has discussed OTLP 1.0.0 release today and decided that we have enough feedback to go ahead with the release.

If you believe we should delay the release please speak up here: https://github.com/open-telemetry/opentelemetry-proto/issues/456

If I don't hear any objections I am going to hit the release button tomorrow.

**Comment by bryce-b** [comment]
https://github.com/open-telemetry/opentelemetry-swift/pull/433
