### ISSUE TITLE
Inconsistent Header Injection Behavior for B3Propagator and W3CBaggagePropagator in URLSessionInstrumentation

### ISSUE THREAD

**Issue by batuhansk** [open-telemetry/opentelemetry-swift#435]
# Issue Description
Currently, there is inconsistent behavior in the injection of headers for B3Propagator and W3CBaggagePropagator in the URLSessionInstrumentation of the opentelemetry-swift repository. While B3Propagator, which extends the TextMapPropagator protocol, successfully injects headers into the HTTP requests made by the client, the same behavior is not observed for W3CBaggagePropagator, which extends the TextMapBaggagePropagator protocol.

# Context
Upon examining the implementation of URLSessionInstrumentation, specifically the URLSessionLogger.swift file, it was observed that the injection of headers for TextMapPropagators occurs on line 171. However, this injection mechanism is not extended to support TextMapBaggagePropagator.

# Comparison with `opentelemetry-java` SDK
Upon comparing the behavior of opentelemetry-swift with the opentelemetry-java SDK, it was found that both B3Propagator and W3CBaggagePropagator extend the TextMapPropagator in the Java SDK. This inconsistency raises the question of whether the differing behavior between the two SDKs is intentional or an oversight.

# Proposed Solution
To ensure consistent behavior across SDKs and address this issue, we propose extending the injection mechanism to support TextMapBaggagePropagator in URLSessionInstrumentation. By incorporating the necessary changes, both B3Propagator and W3CBaggagePropagator should be able to add the appropriate headers to HTTP requests made by the client.

# Contribution and Timeline
We are eager to contribute to resolving this issue and aligning the behavior of opentelemetry-swift with the opentelemetry-java SDK. We kindly request guidance from the project maintainers regarding the best approach to implementing the necessary changes. Once a plan is established, we are committed to working on the solution promptly.

**Comment by batuhansk** [comment]
@nachoBonafonte @bryce-b

**Comment by bryce-b** [comment]
We discussed this proposal in the SIG meeting, and makes sense, if you'd like to submit a PR you're welcome to do it. Thanks!

**Comment by batuhansk** [comment]
> We discussed this proposal in the SIG meeting, and makes sense, if you'd like to submit a PR you're welcome to do it. Thanks!

Thanks for quick reply! I'll open the pull request today.
