### ISSUE TITLE
Inconsistent Access to Parent Span Context Baggage in Custom SpanProcessor

### ISSUE THREAD

**Issue by batuhansk** [open-telemetry/opentelemetry-swift#436]
# Issue Description
When implementing a custom SpanProcessor conforming to the SpanProcessor protocol provided by the `opentelemetry-swift` SDK, there is a requirement to add attributes to a span from the baggage of the parent span context. However, it is not clear how to access the baggage of the parent context in the current implementation.

# Java Equivalent Implementation
In the Java SDK, there is a method called Baggage.fromContext(parentContext:), which allows accessing the baggage of the parent context. This functionality is used in the provided example code to iterate over the baggage entries and add them as attributes to the span.

For reference, in the `opentelemetry-java` SDK, a similar behavior can be achieved using the following implementation:

```swift
public class BaggageSpanProcessor implements SpanProcessor {
  @Override
  public void onStart(Context parentContext, ReadWriteSpan span) {
    Baggage.fromContext(parentContext)
        .forEach((s, baggageEntry) -> span.setAttribute(s, baggageEntry.getValue()));
  }

  @Override
  public boolean isStartRequired() {
    return true;
  }

  @Override
  public void onEnd(ReadableSpan span) {}

  @Override
  public boolean isEndRequired() {
    return false;
  }
}
```

# Swift Implementation
In the Swift implementation provided, there is a usage of `OpenTelemetry.instance.contextProvider.activeBaggage` to access the active baggage. However, it is uncertain whether this will consistently provide the baggage of the parent span context.

```swift
struct BaggageSpanProcessor: SpanProcessor {
    var isStartRequired: Bool {
        true
    }

    var isEndRequired: Bool {
        false
    }

    func onStart(parentContext: OpenTelemetryApi.SpanContext?, span: OpenTelemetrySdk.ReadableSpan) {
        guard let baggage = OpenTelemetry.instance.contextProvider.activeBaggage else { return }

        for entry in baggage.getEntries() {
            span.setAttribute(key: entry.key.name, value: .string(entry.value.string))
        }
    }

    mutating func onEnd(span: OpenTelemetrySdk.ReadableSpan) { }
    mutating func shutdown() {  }
    func forceFlush(timeout: TimeInterval?) { }
}
```

# Expected Behavior
To achieve the same behavior as the Java example, it is important to confirm whether accessing the active baggage using `OpenTelemetry.instance.contextProvider.activeBaggage` will consistently provide the baggage of the parent span context. This clarification will ensure that the Swift implementation accurately reflects the intended functionality.

# Confirmation and Guidance Requested
We kindly request clarification from the `opentelemetry-swift` SDK maintainers regarding the correct approach to accessing the baggage of the parent span context within a custom SpanProcessor. Any guidance or suggestions provided will be greatly appreciated to ensure the proper implementation of this feature.

Thank you for your assistance!

**Comment by batuhansk** [comment]
@nachoBonafonte @bryce-b

**Comment by bryce-b** [comment]
We are discussing this issue in our SIG, and it's not clear to us what the parent context is in java. In the swift SDK the active baggage has nothing to do with the parent span. `OpenTelemetry.instance.contextProvider.activeBaggage` should give you what you're after, but it's related to the current activity (OS Activity) not necessarily the parent span.

**Comment by bryce-b** [comment]
It seems maybe in java the span context and baggage context are being conflated through the general "Context" object, but may still be independent from eachother. I'm not very familiar with the java implementation though.
