### ISSUE TITLE
HTTP Exporter development plan

### ISSUE THREAD

**Issue by zankyn123** [open-telemetry/opentelemetry-swift#437]
I know OtlpHttpTraceExporter is still in development, but I ignored that and still use it in my production environment. 
Recently I have been noticing a lot of crash logs related to the OtlpHttpTraceExporter file, specifically line 36 `self?.pendingSpans.append(contentsOf: sendingSpans)`. I guess this has to do with thread-safety. 
I know you guys are still researching and developing to perfect it, but can you give me some information on perfecting this functionality?

**Comment by bryce-b** [comment]
It looks like we need some thread safety around line 36. thanks for pointing this out!

**Comment by itsniper** [comment]
I believe this was fixed in #497
