### ISSUE TITLE
App crashes when URLSessionInstrumentation is used with AVAssetDownloadTask

### ISSUE THREAD

**Issue by initishbhatt** [open-telemetry/opentelemetry-swift#447]
we use `AVAssetDownloadURLSession` for downloading video assets.However, the tasks used for this `NSURLSession` subclasses as instances of `AVAssetDownloadTask`. Both of these classes declare that the properties originalRequest, currentRequest and response are unavailable.

When using the `URLSessionInstrumentation` app crashes with the following message:
 **Terminating app due to uncaught exception 'NSGenericException', reason: 'AVAssetDownloadTask does not support response property** from code (https://github.com/open-telemetry/opentelemetry-swift/blob/ff57bcc23747bc41e2ab82e57e578e80639fc0a5/Sources/Instrumentation/URLSession/URLSessionInstrumentation.swift#L538).

I'm not sure what would be the solution here. Could you please suggest some alternatives?

**Comment by bryce-b** [comment]
I think it's appropriate to do a check in our instrumentation and NOOP if we detect a AVAssetDownloadTask, since it doesn't support the response attribute, it doesn't seem like this task object provides any information about the streaming content. 

It looks like you'll need to add manual instrumentation for your video streaming though.

**Comment by nachoBonafonte** [comment]
Could you provide some simple code that exercise this issue?, it would help us a lot to fix it as soon as possible. 

For a quick and dirty workaround in the meantime, you can provide `delegateClassesToInstrument` to `URLSessionInstrumentationConfiguration` and only add the delegate classes that are not related to AVAssetDownloadURLSession. It looks like your code is crashing in the session delegate class code.

**Comment by initishbhatt** [comment]
> Could you provide some simple code that exercise this issue?, it would help us a lot to fix it as soon as possible.
> 
> For a quick and dirty workaround in the meantime, you can provide `delegateClassesToInstrument` to `URLSessionInstrumentationConfiguration` and only add the delegate classes that are not related to AVAssetDownloadURLSession. It looks like your code is crashing in the session delegate class code.
Thanks, i'll add the example code for this

**Comment by initishbhatt** [comment]
@bryce-b  not yet, just tested the main branch i am still getting  `Terminating app due to uncaught exception 'NSGenericException', reason: 'AVAssetDownloadTask does not support response property`

**Comment by nachoBonafonte** [comment]
Can you point to the line/method it is crashing? Call stack would be perfect.

Thanks

**Comment by initishbhatt** [comment]
```
Task <38BD4CBD-37D7-4FDE-B9FF-F2E77F75AA54>.<1> finished with error [-1] Error Domain=NSURLErrorDomain Code=-1 "(null)" UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundAVAssetDownloadTask <38BD4CBD-37D7-4FDE-B9FF-F2E77F75AA54>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <38BD4CBD-37D7-4FDE-B9FF-F2E77F75AA54>.<1>}
2023-09-04 14:43:10.935246+0530 Share Alpha[83887:2447234] Task <044A0AA5-73F4-43A9-909D-0D96E511B333>.<2> finished with error [-11800] Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedDescription=The operation could not be completed, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <044A0AA5-73F4-43A9-909D-0D96E511B333>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundAVAssetDownloadTask <044A0AA5-73F4-43A9-909D-0D96E511B333>.<2>"
), NSLocalizedFailureReason=An unknown error occurred (-16090)}
2023-09-04 14:43:10.975576+0530 Share Alpha[83887:2446810] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'AVAssetDownloadTask does not support response property'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000117b2e330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000010cfb1274 objc_exception_throw + 56
	2   CFNetwork                           0x000000010c0a7118 _CFStreamErrorFromCFError + 357372
	3   App                                 0x0000000103de081c $s25URLSessionInstrumentationAAC10urlSession33_F818B2EEA90FD328A0D707D80B0155ACLL_4task20didCompleteWithErrorySo12NSURLSessionC_So0S4TaskCs0R0_pSgtF + 816
	4   App                                 0x0000000103ddbff0 $s25URLSessionInstrumentationAAC47injectTaskDidCompleteWithErrorIntoDelegateClass33_F818B2EEA90FD328A0D707D80B0155ACLL3clsyyXlXp_tFyyp_So12NSURLSessionCSo0vD0Cs0H0_pSgtcfU_ + 520
	5   App                                 0x0000000103ddc8c4 $sypSo12NSURLSessionCSo0A4TaskCs5Error_pSgIegnggg_yXlAbDSo7NSErrorCSgIeyByyyy_TR + 200
	6   CFNetwork                           0x000000010bf9c0e0 CFNetwork + 49376
	7   libdispatch.dylib                   0x000000011710c528 _dispatch_call_block_and_release + 24
	8   libdispatch.dylib                   0x000000011710dd50 _dispatch_client_callout + 16
	9   libdispatch.dylib                   0x000000011711e808 _dispatch_main_queue_drain + 1316
	10  libdispatch.dylib                   0x000000011711e2d4 _dispatch_main_queue_callback_4CF + 40
	11  CoreFoundation                      0x0000000117a91784 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	12  CoreFoundation                      0x0000000117a8bde4 __CFRunLoopRun + 1912
	13  CoreFoundation                      0x0000000117a8b254 CFRunLoopRunSpecific + 584
	14  GraphicsServices                    0x000000011ccc3c9c GSEventRunModal + 160
	15  UIKitCore                           0x000000012767eff0 -[UIApplication _run] + 868
	16  UIKitCore                           0x0000000127682f3c UIApplicationMain + 124
	```

**Comment by initishbhatt** [comment]
i used the same fix code in the function  private func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)

```
if let avAssetTaskClass = Self.avAssetDownloadTask,
           task.isKind(of: avAssetTaskClass) {
            return
        }
```
and its working as expected

**Comment by nachoBonafonte** [comment]
Could you check with the code in the  #458 PR, I think this is the proper fix for the issue

**Comment by initishbhatt** [comment]
this works :)
