### ISSUE TITLE
Following Semantic versioning

### ISSUE THREAD

**Issue by mbentin-cariad** [open-telemetry/opentelemetry-swift#451]
The last release did not follow semantic versioning. 
When there is a breaking change the major version needs to be increased, it is used by the swift package manager to resolve dependencies and keep a stable state in the code base. 

[Documentation](https://semver.org/)

Proposed solutions:

1. Follow semantic versioning for releases
2. Big disclaimer at the beginning of the README mentioning this library does not follow semantic versioning

**Comment by nachoBonafonte** [comment]
There is nothing wrong about the versioning here, as there is no breaking API changes. 

The breaking change is referred to compatibility between the library and the OpenTelemetry collector, if you happen to use an old collector in your backend it won't work.

**Comment by mbentin-cariad** [comment]
Sorry I should have pointed it out. 
The problem occurs in the protocol `EventBuilder`
A new function was added: 

```swift 
func setData(_ attributes: [String: AttributeValue]) -> Self
```
