### ISSUE TITLE
Enable Library Evolution Support by Resolving File Naming Ambiguities and Replacing Reachability.swift

### ISSUE THREAD

**Issue by batuhansk** [open-telemetry/opentelemetry-swift#453]
# Problem Statement
We are currently using the `opentelemetry-swift` SDK in our projects and have encountered some limitations that prevent us from building and distributing it as an XCFramework with library evolution enabled. The issues lie mainly in the file naming conventions and dependencies:

Targets such as `NetworkStatus` and `URLSessionInstrumentation` have a file named identically to their target names, which causes naming ambiguities.

The `Reachability.swift` dependency serves a similar purpose to Apple's `NWPathMonitor`, which can lead to redundancy and also prevents library evolution.

# Proposed Solutions
**File Naming Ambiguity**: Renaming the files that have the same name as their targets to avoid naming conflicts. For instance, changing NetworkStatus.swift to NetworkStatusAPI.swift or any other name that doesn't conflict with the target name, or changing the target name is also an another option.

**Reachability Dependency**: Replace the `Reachability.swift` dependency with Apple's `NWPathMonitor`. This would not only remove a third-party dependency but also enable library evolution capabilities. To use `NWPathMonitor`, the minimum required iOS version should be bumped to *12.0*.

# Benefits
**Compatibility**: Distributing the SDK as an XCFramework with library evolution will make it compatible with higher versions of Xcode.

**Reduced Dependencies**: Using native Apple libraries like NWPathMonitor instead of third-party libraries will make the SDK lighter and more aligned with Apple's ecosystem.

**Forward Compatibility**: Library evolution support allows forward compatibility with future Swift compiler versions without requiring SDK recompilation.

**Easier Maintenance**: Using native libraries like NWPathMonitor and reducing file-naming ambiguities would make the SDK easier to maintain and troubleshoot.

# Conclusion
Enabling library evolution support in the `opentelemetry-swift` SDK by resolving these issues will make it more robust and compatible for varied usage scenarios. We recommend addressing these issues to improve the overall utility and maintainability of the SDK.

We're eager to contribute to solving these problems and welcome guidance on the best steps forward. Thank you for your attention to this matter.

**Comment by jhoongo** [comment]
@bryce-b any update on this? Are we planning to release the SDKs as XCFramework as well?

The reason I'm asking is that due to the [SPM issue](https://stackoverflow.com/questions/68408989/swift-package-manager-target-based-dependency) (which resolves entire dependencies of `Package.swift`), I'm resolving all unnecessary dependencies that I did not intend to use in my app. Which doesn't compile and isn't bundled into my app, but still significantly impact CI/build time.

Would love to see if the SDK will be published as XCFramework so that I can pick and choose only the necessary targets I need.

**Comment by bryce-b** [comment]
Hi @jhoongo,
Sorry for the lack of updates on this ticket, I've been busy with internal projects. It's unlikely that we will be publishing an XCFramework, but we would like to make it possible for 3rd parties to do so. It appears that there may be some [conflicts](https://github.com/apple/swift-nio/issues/1257) with our SwiftNIO dependency in making that possible. It looks like this dependency issue needs to get resolved before library evolution can be enabled.

**Comment by batuhansk** [comment]
Hi @jhoongo and @bryce-b,

For our own internal usage, I've successfully extracted XCFramework with library evolution support, but as I proposed in this issue, it requires some modifications for some targets and 3rd party dependencies.

Once I find the spare time, I'd like to propose it and open its pull request here as well.

**Comment by jhoongo** [comment]
Hey @bryce-b / @batuhansk , thanks for the update. Let spend some time on building XCFramework by myself, and see if that works. @batuhansk Would you be able to share any insight or experience that you had while building it for your own? That would be greatly appreciated 🙏 🙇

**Comment by nachoBonafonte** [comment]
In this thread a user uses mint for the xcframework: https://github.com/open-telemetry/opentelemetry-swift/issues/344

**Comment by batuhansk** [comment]
It seems that the library evolution support brought by @bryce-b with #482 PR has been implemented. Closing this issue. Thanks 🙌🏻

**Comment by jhoongo** [comment]
@batuhansk Would you be able to share the commands/tools to generate XCFramework for the OpenTelemetrySdk? I was using `mint`, but it keeps failing with the following error :( 

```
debug: evaluating manifest for 'opentelemetry-swift' v. unknown 
error: missingKey("product_type")
debug: evaluating manifest for 'opentelemetry-swift' v. unknown 
error: missingKey("product_type")
Error: fatalError
```

**Comment by jhoongo** [comment]
> @batuhansk Would you be able to share the commands/tools to generate XCFramework for the OpenTelemetrySdk? I was using `mint`, but it keeps failing with the following error :(
> 
> ```
> debug: evaluating manifest for 'opentelemetry-swift' v. unknown 
> error: missingKey("product_type")
> debug: evaluating manifest for 'opentelemetry-swift' v. unknown 
> error: missingKey("product_type")
> Error: fatalError
> ```

So this issue wasn't related to OpenTelemetry repo, it was Xcode 15 compatibility issue with `swift-create-xcframework`. ref: https://github.com/unsignedapps/swift-create-xcframework/pull/93
