### ISSUE TITLE
HTTP exporter auth

### ISSUE THREAD

**Issue by emoragaf** [open-telemetry/opentelemetry-swift#455]
Hello, first time working with swift. And I'm building a thin wrapper around this lib, using the OTLP http exporter for traces

I need to set some headers for authentication, a case I feel is common enough, but not covered in the example.

Any pointers on how to accomplish it?

**Comment by bryce-b** [comment]
You need to set it in the headers parameter in the [`OtlpConfiguration`](https://github.com/open-telemetry/opentelemetry-swift/blob/main/Sources/Exporters/OpenTelemetryProtocolCommon/common/OtlpConfiguration.swift) object before passing it to your exporter.

**Comment by emoragaf** [comment]
@bryce-b I don't get the option listed to pass config to the exporter 🤔 (I do see it for the grpc exporter in contrast) could you give me an example for it please

**Comment by bryce-b** [comment]
https://github.com/open-telemetry/opentelemetry-swift/issues/457

**Comment by bryce-b** [comment]
@emoragaf the HTTP client should accept http headers now.

**Comment by nwagu** [comment]
Hi, is there any way to configure dynamic authentication for http exporter? That is, to use tokens that need to be refreshed periodically?
