### ISSUE TITLE
Allow the ObservableLongGauge and ObservableDoubleGauge close the measurement

### ISSUE THREAD

**Issue by hunguyenaxon** [open-telemetry/opentelemetry-swift#467]
According to Android's library, the `ObservableLongGauge` ([link](https://github.com/open-telemetry/opentelemetry-java/blob/5ccc7fccb3fd0bdfa902bfea7bcee43384cdcf3e/api/all/src/main/java/io/opentelemetry/api/metrics/ObservableLongGauge.java#L16)) and `ObservableDoubleGauge` ([link](https://github.com/open-telemetry/opentelemetry-java/blob/5ccc7fccb3fd0bdfa902bfea7bcee43384cdcf3e/api/all/src/main/java/io/opentelemetry/api/metrics/ObservableDoubleGauge.java)) must have the ability to remove the registered callback After this is called, the callback won't be invoked on future collections.

Reference from Android:
```
/**
 * A reference to an observable instrument registered with {@link
 * DoubleGaugeBuilder#buildWithCallback(Consumer)}.
 *
 * @since 1.10.0
 */
public interface ObservableDoubleGauge extends AutoCloseable {

  /**
   * Remove the callback registered via {@link DoubleGaugeBuilder#buildWithCallback(Consumer)}.
   * After this is called, the callback won't be invoked on future collections. Subsequent calls to
   * {@link #close()} have no effect.
   *
   * <p>Note: other callbacks registered to the instrument with the same identity are unaffected.
   *
   * @since 1.12.0
   */
  @Override
  default void close() {}
}
```

**Comment by hunguyenaxon** [comment]
I fixed that in my forked repo. I'm going to make PR on that by tomorrow

**Comment by kevinearls** [comment]
@bryce-b this looks like it can also be closed
