### ISSUE TITLE
Allow the `ObservableDoubleCounter`, `ObservableDoubleUpDownCounter`, `ObservableLongCounter`, `ObservableLongUpDownCounter` close the measurement

### ISSUE THREAD

**Issue by hunguyenaxon** [open-telemetry/opentelemetry-swift#469]
`ObservableDoubleCounter`, `ObservableDoubleUpDownCounter`, `ObservableLongCounter` and `ObservableLongUpDownCounter` must have the ability to remove the registered callback.
 After this is called, the callback won't be invoked on future collections.

It should be done together with https://github.com/open-telemetry/opentelemetry-swift/issues/467, when we implement `close()` function into ObservableInstrumentSdk

**Comment by hunguyenaxon** [comment]
I fixed that in my forked repo. I'm going to make PR on that by tomorrow

**Comment by kevinearls** [comment]
@bryce-b This can be closed since the PR is merged
