### ISSUE TITLE
Custom baggage don't show up in the collector

### ISSUE THREAD

**Issue by baltisso** [open-telemetry/opentelemetry-swift#477]
I'm trying to add custom baggage to my spans like this:
```
let mySpan = tracerProvider.spanBuilder(spanName: "trace my span").startSpan()

let myBaggageBuilder = DefaultBaggage.baggageBuilder()
myBaggageBuilder(key: EntryKey(name: "baggage my key")!, value: EntryValue(string: "baggage my value")!, metadata: nil)
OpenTelemetry.instance.contextProvider.setActiveBaggage(myBaggageBuilder.build())
        
mySpan.end()
```
But it doesn't show up in the OTel Collector. Am I doing it wrong or is it a bug? (If there's is a custom baggage example, please point me to it 🙂)

**Comment by baltisso** [comment]
I still haven't had any luck trying to get this to work. Can anyone please provide me with a bit of direction here? Any hint would be eternally valued! 🙏

**Comment by nachoBonafonte** [comment]
Hi @baltisso, sorry for the delay in answering, what are your expectations here? Baggage is just contextual information that moves between spans, it is used for propagating  information but is not part of the span itself, so it is not reported along with it. If you want for it to be reported with the span you must assign the baggage info as tags to the span. Have you seen any difference in other opentelemetry implementations?

[https://opentelemetry.io/docs/concepts/signals/baggage/](https://opentelemetry.io/docs/concepts/signals/baggage/)
[https://opentelemetry.io/docs/specs/otel/baggage/api/](https://opentelemetry.io/docs/specs/otel/baggage/api/)
