### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by xxZap** [open-telemetry/opentelemetry-swift#48]
Hello and thanks for your job, you're doing great!
I'm an iOS developer and I was wondering if it was possible to use this library for a mobile application.
I was pretty happy to see the last commits about the Zipkin exporter but after I imported the package on my project I realize that it seems to be only for the macOS environment, isn't it?

On my side, I can say I'm not very confident with this kind of development or technology, in fact, I'm asking you if it is possible or not.

**Comment by nacho-undefinedlabs** [comment]
Hi @xxZap , definitely it can be used for a mobile application, in fact it should work in any platform that supports Swift. The issue you saw in Zipkin exporter was an oversight on my side, I have prepared a fix for it.

**Comment by xxZap** [comment]
This is awesome, thank you!
