### ISSUE TITLE
SDKResourceExtension is reporting the wrong telemetry.sdk.version

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-swift#490]
https://github.com/open-telemetry/opentelemetry-swift/blob/10563f42bb28b5a28add70241c7efccf16477300/Sources/Instrumentation/SDKResourceExtension/DataSource/TelemetryDataSource.swift#L21

This shouldn't be reporting the app version the sdk is embedded in, but the value in the opentemetry-swift version file.

**Comment by vvydier** [comment]
Fixed it with PR https://github.com/open-telemetry/opentelemetry-swift/pull/491
