### ISSUE TITLE
Build error on executables that have Opentracing dependency

### ISSUE THREAD

**Issue by vvydier** [open-telemetry/opentelemetry-swift#493]
I am noticing this build error on most of the executables in the repo with the new Xcode version. 
Do we need to update Opentracing as the build error seems to reference that.

Showing Recent Errors Only

Build target Opentracing with configuration Debug

ld: Undefined symbols:
  ___llvm_profile_runtime, referenced from:
      ___llvm_profile_runtime_user in Opentracing.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols:

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by nachoBonafonte** [comment]
Yes, that is related to code coverage, the opentracing library doesn't support it. The latest Xcode likes to enable them by default when building for debug, you should manually disable them in Xcode
