### ISSUE TITLE
StableOtlpHTTPMetricExporter not working

### ISSUE THREAD

**Issue by Archish27** [open-telemetry/opentelemetry-swift#500]
The following snippet is used for metric - 

```swift
let otlpMetricExporter = StableOtlpHTTPMetricExporter(
    endpoint: URL(string: "http://example.com/v1/metrics")!,
    config: OtlpConfiguration(timeout: TimeInterval(10000),
                              headers: [("Access-Control-Allow-Headers", "*")]))

OpenTelemetry.registerStableMeterProvider(meterProvider: StableMeterProviderSdk
    .builder()
    .registerMetricReader(reader:
                            StablePeriodicMetricReaderBuilder(exporter: otlpMetricExporter)
                                .setInterval(timeInterval: 5)
                                .build()).build())
```

Unable to see `/v1/metrics` endpoint getting hit.

**Comment by bryce-b** [comment]
Hi @Archish27 I believe you need to add a "view" for metrics to be processed. Take a look at the [stable metrics sample](https://github.com/open-telemetry/opentelemetry-swift/blob/main/Examples/Stable%20Metric%20Sample/main.swift#L47) on how to add a view.

**Comment by Archish27** [comment]
Hey @bryce-b I added `registerView` the following is the code snippet

```swift
OpenTelemetry.registerStableMeterProvider(meterProvider: StableMeterProviderBuilder()
            .registerView(selector: InstrumentSelector.builder().setInstrument(name: ".*").build(), view: StableView.builder().build())
            .registerMetricReader(reader: StablePeriodicMetricReaderBuilder(exporter: StableOtlpHTTPMetricExporter(
                endpoint: URL(string: builder.target! + "/v1/metrics")!,
                config: OtlpConfiguration())) as! StableMetricReader)
                .build()
        )
```

Getting exception `Could not cast value of type 'OpenTelemetrySdk.StablePeriodicMetricReaderBuilder' (0x10147f378) to 'OpenTelemetrySdk.StableMetricReader' (0x1f1d08310).` Can you please help am I missing something here?

**Comment by bryce-b** [comment]
you need to call `build()` on the StablePeriodicMetricReaderBuilder to receive a StablePeriodicMetricReader

**Comment by nachoBonafonte** [comment]
any updates here, is it working after the `build()` call?
