### ISSUE TITLE
Opentelemetry Data persistency

### ISSUE THREAD

**Issue by vitanie** [open-telemetry/opentelemetry-swift#505]
What happens if the OpenTelemetry collector cannot send data？Data loss happens，how to  Data persistency?

**Comment by bryce-b** [comment]
Hi @vitanie, 
We have an exporter that handles data persistence : https://github.com/open-telemetry/opentelemetry-swift/tree/main/Sources/Exporters/Persistence

**Comment by nachoBonafonte** [comment]
OtlpHttpExporter also has some simple in-memory retries.
