### ISSUE TITLE
1.9.2 release with crash fix

### ISSUE THREAD

**Issue by ypopovych** [open-telemetry/opentelemetry-swift#529]
Hello,

Could you, please, do a new release. 

https://github.com/open-telemetry/opentelemetry-swift/pull/523 PR fixes crashes in the URLSession and it would be great to have release version with it.

Thanks,
Yehor

**Comment by nachoBonafonte** [comment]
We have the SIG meeting today, I will bring this topic to the meeting and will take the decision, but I don't expect any objection, we try to be as useful as possible releasing fix versions when asked.

**Comment by nachoBonafonte** [comment]
It has just been released.
