### ISSUE TITLE
Regarding OTLP Log collector limitations

### ISSUE THREAD

**Issue by batuhansk** [open-telemetry/opentelemetry-swift#538]
Hey there,

I noticed that the OTLP Log collector (with HTTP exporter) is labeled as experimental in the README file. Could you provide some insights into its current limitations and what users should be aware of when using it? It would be great to have a clearer understanding before incorporating it into our projects.

Thanks!

**Comment by batuhansk** [comment]
Any comments? @bryce-b @nachoBonafonte  🙏🏼

**Comment by nachoBonafonte** [comment]
Hi @batuhansk,
It should be considered beta quality now, it can be used but you could still find some issues (none reported currently)
