### ISSUE TITLE
Allow configuration of Zipkin Exporter endpoint

### ISSUE THREAD

**Issue by xxZap** [open-telemetry/opentelemetry-swift#55]
Hello guys,
thanks for your work!

I noticed that the `ZipkinTraceExporter` needs a `ZipkinTraceExporterOptions` to be instantiated, which contains the endpoint to be used.
It seems that this struct, the `ZipkinTraceExporterOptions` is not usable from outside the package because it has no public initializer and/or editable `endpoint` value.

On my own, I edited in this way but I'm wondering if you are already planning a fix, so I didn't have the chance to test it yet.

```
public struct ZipkinTraceExporterOptions {
    let endpoint: String
    let timeoutSeconds: TimeInterval
    let serviceName: String
    let useShortTraceIds: Bool

    public init(endpoint: String = "http://localhost:9411/api/v2/spans",
                serviceName: String = "Open Telemetry Exporter",
                timeoutSeconds: TimeInterval = 10.0,
                useShortTraceIds: Bool = false) {

        self.endpoint = endpoint
        self.serviceName = serviceName
        self.timeoutSeconds = timeoutSeconds
        self.useShortTraceIds = useShortTraceIds
    }
}
```

**Comment by nachoBonafonte** [comment]
It's true, your solution looks good. You can make a pull request and I can approve and merge.

**Comment by xxZap** [comment]
@nachoBonafonte 
Thank you, I did it here [Pull Request](https://github.com/open-telemetry/opentelemetry-swift/pull/57) 
but it doesn't pass the CLA signature.
I followed the instructions to enable my GitHub account and II signed, but the commit is still locked

**Comment by xxZap** [comment]
I got my easyCLA's license. I think now is ready to be reviewed
