### ISSUE TITLE
Add Alolita Sharma as a triager for OTel Swift 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-swift#574]
Create @swift-triagers list. Add Alolita Sharma as a triager to the @swift-triagers list.

**Comment by nachoBonafonte** [comment]
I have no rights to create the group as it must be part of OpenTelemetry organisation

**Comment by alolita** [comment]
Thanks @svrnm for the link. Will open up an issue on the community repo.

**Comment by bryce-b** [comment]
ticket created https://github.com/open-telemetry/community/issues/2279

**Comment by arminru** [comment]
Created @open-telemetry/swift-triagers per https://github.com/open-telemetry/community/issues/2279 and added @alolita.
