### ISSUE TITLE
No such module 'OpenTelemetryProtocolExporter'

### ISSUE THREAD

**Issue by EslamAbotaleb** [open-telemetry/opentelemetry-swift#589]
When I try to import OpenTelemetryProtocolExporter there message displays No such module 'OpenTelemetryProtocolExporter' and I already added OpenTelemetryProtocolExporter based on open telemetry

**Comment by bryce-b** [comment]
The OTLP exporter is separated into several different packages: `OpenTelementryProtocolExporterHttp`, `OpenTelementryProtocolExporterGrpc`, and `OpenTelementryProtocolExporterCommon`. To use the OTLP exporter you'll need to chose either the GRPC or HTTP implementation and import that along with the Common module.
