### ISSUE TITLE
OTEL_SWIFT_SDK_VERSION is out of date

### ISSUE THREAD

**Issue by beekhc** [open-telemetry/opentelemetry-swift#600]
In [Sources/OpenTelemetrySdk/Version.swift](https://github.com/open-telemetry/opentelemetry-swift/blob/e6f89eeaa1ccc97b9f8a9759bef519ba071a54d9/Sources/OpenTelemetrySdk/Version.swift#L7), `OTEL_SWIFT_SDK_VERSION` seems to be behind the actual release version.

I see that a previous attempt at automatically updating it was reverted. Maybe some other kind of check could be added to keep it in sync?

**Comment by ArielDemarco** [comment]
It looks like this issue was resolved in this [PR](https://github.com/open-telemetry/opentelemetry-swift/pull/610) as the workflow for release will update the `Version.swift` file; it'll likely be fixed in the next release.

**Comment by ArielDemarco** [comment]
**Update**: seems like the [latest release](https://github.com/open-telemetry/opentelemetry-swift/releases/tag/1.11.0) fixed that issue as the [Version.swift](https://github.com/open-telemetry/opentelemetry-swift/blob/1.11.0/Sources/OpenTelemetrySdk/Version.swift) matches the actual version (1.11.0)
