### ISSUE TITLE
metric data max and min value 

### ISSUE THREAD

**Issue by samllOranges** [open-telemetry/opentelemetry-swift#611]
The current version of opentelemetry-swift is 1.10.1.
When will a new release be released to fix the problem that the Exported metric data does not have the maximum and minimum values? The MetricsAdapter class in the example has been fixed, but the release version has not.
I am now using spm to manage the SDK, but I am not very familiar with it. In addition to using the latest release version, I don’t know how to update to the version that has solved the maximum and minimum value problems of the Exported metric data.
It’s urgent, and I look forward to your reply. Thank you!

**Comment by bryce-b** [comment]
Sorry for the delay, there were other factors holding up the release we were trying to resolve, but we'll be moving forward with a release shortly.
