### ISSUE TITLE
Concurrency issues with `SpanData` modification leading to vrashes

### ISSUE THREAD

**Issue by ArielDemarco** [open-telemetry/opentelemetry-swift#630]
Greetings! Our SDK uses `OpenTelemetryApi` and `OpenTelemetrySdk`, and we've encountered an issue related to crashes caused by concurrency problems, specifically when working with `SpanData`. I've only found [this documentation](https://github.com/open-telemetry/opentelemetry-specification/blob/8d043e9763aa3818b1ebb904a6c6efb5746e531b/specification/trace/api.md#concurrency) around concurrency, so i'm not pretty sure if this is or not the expected behavior. When testing directly with the `Span`, this issue does not occur (probably because adding events or attributes occur inside a `Lock`). I've added some tests to verify both cases:
```swift
class OpenTelemetryConcurrencyTests: XCTestCase {
    /// Crashes :(
    func test_spanDataShouldntCrashOnBeingModifiedFromDifferentThreads() {
        var data = SpanData(
            traceId: .random(),
            spanId: .random(),
            name: #function,
            kind: .internal,
            startTime: Date(),
            endTime: Date().addingTimeInterval(100)
        )
        
        DispatchQueue.concurrentPerform(iterations: Int.random(in: 100...150), execute: { run in
            data.settingAttributes([UUID().uuidString: .int(run)])
        })
    }
    
    /// Works!
    func test_spanShoudlntCrashOnBeingModifiedFromDifferentThreads() {
        let tracer = TracerProviderSdk()
        let builder = SpanBuilderSdk(spanName: #function, instrumentationScopeInfo: .init(), tracerSharedState: tracer.sharedState, spanLimits: tracer.getActiveSpanLimits())
        let span = builder.startSpan()

        DispatchQueue.concurrentPerform(iterations: Int.random(in: 100...150), execute: { run in
            span.setAttribute(key: UUID().uuidString, value: .int(run))
        })
    }
}
```

**Comment by nachoBonafonte** [comment]
Hi @ArielDemarco, yes that is the expected behavior, SpanData is not thought to be modified concurrently from different threads. SpanData is an struct that represents all the data collected by the Span, usually generated when it has been exported, so it should not be modified as a general rule.

**Comment by ArielDemarco** [comment]
Hey @nachoBonafonte! Thanks for the quick response and for the clarification around `SpanData` usage.

Considering that, I conducted a deeper investigation into the issue to see what could be happening... and I found out that we don’t modify `SpanData` (we only read from it, and that's when our crash is happening).

Digging a bit deeper while running Thread Sanitizer, I discovered a _potential problem_: it appears that one thread is adding `attributes` to a `Span` (a write operation protected by the `attributesSyncLock`) while another thread is attempting to access these attributes during `toSpanData()`. Probably this data race can lead to `SpanData` being created with potentially inconsistent or corrupted data.

As an experiment, I wrapped the `toSpanData()` method call in the same lock (`attributesSyncLock`) that is used to modify `attributes`. This seems to have eliminated the data race in my tests, although I recognize this may not be the ideal long-term solution

**Comment by nachoBonafonte** [comment]
Yes, that is a real problem, and as you said it should be protected by that lock. Usually toSpanData is called only on export so this is usually not an issue because as the span has ended it won't accept more attributes so they are no modified. 

But there are some real use cases that may need to call toSpanData during the lifetime of a span ( if you want to save intermediate state in case of a crash, to not lose information in the case the span is never ended, ...). 

So yes, I think your fix is good and should be added to the library, would you mind creating a PR?

**Comment by ArielDemarco** [comment]
Already raised the PR @nachoBonafonte
