### ISSUE TITLE
Add trace propagation using environment variables

### ISSUE THREAD

**Issue by nachoBonafonte** [open-telemetry/opentelemetry-swift#78]
It is very useful for tracing solutions which include different binaries on the same machine. Having a ready to use solution in the framework is a plus

**Comment by SergeyKanzhelev** [comment]
spec for it: https://github.com/carlosalberto/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md#user-content-general-sdk-configuration:~:text=Propagators%20to%20be%20used%20as%20a%20comma%20separated%20list
